[package]
name = "nextcloud-ldap"
description = "Nextcloud LDAP server — synchronizes users and groups from Keycloak to provide Nextcloud-compatible LDAP attribute sets for user and group enumeration workflows"
homepage = "https://rechenknecht.net/giz/keycloak/keycloak-ldap-server/-/tree/main/nextcloud-ldap"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = "~1.0.102"
giz-ldap-lib = { path="../ldap-lib" }
keycloak = "~26.5.200"
tokio = { version = "~1.50.0", features = ["io-util"] }
